package com.bancosantander.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FechasProceso implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Fecha Corte de Pago")
	private java.util.Date fechaCorte;
	@org.kie.api.definition.type.Label("Fecha límite Pago")
	private java.util.Date fechaLimitePago;
	@org.kie.api.definition.type.Label("Fecha de Pago")
	private java.util.Date fechaPago;

	/**
	 * Constructor por defecto
	 */
	public FechasProceso() {
	}
	/**
	 * @return
	 */
	public java.util.Date getFechaCorte() {
		return this.fechaCorte;
	}
	/**
	 * @param date
	 */
	public void setFechaCorte(java.util.Date fechaCorte) {
		this.fechaCorte = fechaCorte;
	}
	/**
	 * @return
	 */
	public java.util.Date getFechaLimitePago() {
		return this.fechaLimitePago;
	}
	/**
	 * @param date
	 */
	public void setFechaLimitePago(java.util.Date fechaLimitePago) {
		this.fechaLimitePago = fechaLimitePago;
	}
	/**
	 * @return
	 */
	public java.util.Date getFechaPago() {
		return this.fechaPago;
	}
	/**
	 * @param date
	 */
	public void setFechaPago(java.util.Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public FechasProceso(java.util.Date fechaCorte,
			java.util.Date fechaLimitePago, java.util.Date fechaPago) {
		this.fechaCorte = fechaCorte;
		this.fechaLimitePago = fechaLimitePago;
		this.fechaPago = fechaPago;
	}

}