/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

import java.util.Objects;
/**
 * Retrieves the domiciliation status detail information
 */
public class DomiciliationDetail {
  
  private String id = null;

  /**
   * Indicates the status of the domiciliation.   * &#x60;ACTIVE&#x60; -  Indicates that status for domiciliation is active in this moment.   * &#x60;INACTIVE&#x60; - Indicates that the domiciliation status is inactive. 
   */
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    INACTIVE("INACTIVE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
  
  } 

  private StatusEnum status = null;

  private java.util.Date operationDate = null;

   /**
   * Indicates the domiciliation identifier.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

   /**
   * Indicates the status of the domiciliation.   * &#x60;ACTIVE&#x60; -  Indicates that status for domiciliation is active in this moment.   * &#x60;INACTIVE&#x60; - Indicates that the domiciliation status is inactive. 
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

   /**
   * Indicates the date on which the domiciliation was contracted. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html
   * @return operationDate
  **/
  public java.util.Date getOperationDate() {
    return operationDate;
  }

  public void setOperationDate(java.util.Date operationDate) {
    this.operationDate = operationDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DomiciliationDetail domiciliationDetail = (DomiciliationDetail) o;
    return Objects.equals(this.id, domiciliationDetail.id) &&
        Objects.equals(this.status, domiciliationDetail.status) &&
        Objects.equals(this.operationDate, domiciliationDetail.operationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, operationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DomiciliationDetail {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    operationDate: ").append(toIndentedString(operationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
