/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

import java.util.Objects;
/**
 * Retrieves the payment card basic information
 */
public class PaymentDetail {
  private AllOfPaymentDetailAmountPayment amountPayment = null;

  private AllOfPaymentDetailMinimumAmount minimumAmount = null;

  private java.util.Date operationDate = null;

   /**
   * Indicates the amount paid.
   * @return amountPayment
  **/
  public AllOfPaymentDetailAmountPayment getAmountPayment() {
    return amountPayment;
  }

  public void setAmountPayment(AllOfPaymentDetailAmountPayment amountPayment) {
    this.amountPayment = amountPayment;
  }

   /**
   * Indicates the minimum payment amount
   * @return minimumAmount
  **/
  public AllOfPaymentDetailMinimumAmount getMinimumAmount() {
    return minimumAmount;
  }

  public void setMinimumAmount(AllOfPaymentDetailMinimumAmount minimumAmount) {
    this.minimumAmount = minimumAmount;
  }

   /**
   * Indicates the date on which the payment was made. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html
   * @return operationDate
  **/
  public java.util.Date getOperationDate() {
    return operationDate;
  }

  public void setOperationDate(java.util.Date operationDate) {
    this.operationDate = operationDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentDetail paymentDetail = (PaymentDetail) o;
    return Objects.equals(this.amountPayment, paymentDetail.amountPayment) &&
        Objects.equals(this.minimumAmount, paymentDetail.minimumAmount) &&
        Objects.equals(this.operationDate, paymentDetail.operationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amountPayment, minimumAmount, operationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentDetail {\n");
    
    sb.append("    amountPayment: ").append(toIndentedString(amountPayment)).append("\n");
    sb.append("    minimumAmount: ").append(toIndentedString(minimumAmount)).append("\n");
    sb.append("    operationDate: ").append(toIndentedString(operationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
